openapi: 3.0.0
info:
  title: Guardias IES La Vereda API
  version: 1.0.0
tags:
  - name: Docente Views
    description: Operation related with docents
  - name: Document Actions
    description: Operation related with documents
  - name: Login Actions
    description: Operation related with login
paths:
  /docentes:
    get:
      summary: Get all docents
      tags:
        - Docente Views
      responses:
        '200':
          description: List of docents
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocentesResponse'
components:
  schemas:
    DocentesResponse:
      type: array
      description: Docente Response
      items:
        $ref: '#/components/schemas/Docente'
    Docente:
      type: object
      description: Docente model
      properties:
        id:
          type: integer
          format: int64
          description: ID docente
          example: 452346
