openapi: 3.0.0
info:
  title: Guardias IES La Vereda API
  version: 1.0.0
tags:
  - name: Docente Views
    description: Operation related with docents
  - name: Document Actions
    description: Operation related with documents
  - name: Login Actions
    description: Operation related with login
paths:
  /teachers:
    get:
      summary: Get all teachers
      description: Get all teachers
      operationId: getAllTeachers
      tags:
        - Docente Views
      responses:
        '200':
          description: List of docents
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocentesResponse'
  /document/updateXML:
    post:
      summary: Update XML
      description: Update XML data using a file
      operationId: updateXML
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful update
components:
  schemas:
    DocentesResponse:
      type: array
      description: Docente Response
      items:
        $ref: '#/components/schemas/Docente'
    Docente:
      type: object
      description: Docente model
      properties:
        id:
          type: integer
          format: int64
          description: ID docente
          example: 452346
