spring:
  application:
    name: guardiaslavereda
  flyway:
    locations: classpath:migration/versions
    baselineOnMigrate: true
    baselineVersion: 0
    user: sa
    password: root
  datasource:
    username: sa
    password: root
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:guardiadb
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        envers:
          enabled: true
          store_data_at_delete: true
          audit_table_suffix: _aud
        ddl-auto: update
  security:
    ldap:
      url: ldap://localhost:389
      base: ieslavereda,dc=local
      username: cn=admin,dc=ieslavereda,dc=local
      password: 123456789
server:
  port: 8081