spring:
  application:
    name: guardiaslavereda
  datasource:
    username: sa
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/guardias
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        envers:
          enabled: true
          store_data_at_delete: true
          audit_table_suffix: _aud
  flyway:
    locations: classpath:migration/versions
    baselineOnMigrate: true
    baselineVersion: 0
    user: sa
    password: root
server:
  port: 8081